### ISSUE TITLE
Usage message

### ISSUE THREAD

**Issue by wawwior** [BotulToxin/RoyalGrenadier#7]
Is there a way to implement custom exception handling?
Tried to do it myself but most exceptions like the ones thrown by argument types are being caught somewhere high up in the nms command handling.
Also, this makes getShowUsageOnFail useless, since it only executes when an Exception is caught in the wrapper, which only happens when the exception is thrown in one of the executes() subcommand nodes.

**Comment by BotulToxin** [comment]
Sorry for the very late response.

Custom exception handling? If the exceptions thrown by ArgumentTypes aren't being caught by Grenadier's wrapper, then something's wrong.

As of now though, I don't believe custom exception handling is possible
